// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA30YQU_UAML4nkyhJycTuXtSsvr1-PzJ0',
    appId: '1:699975908686:web:094cd4fcb0068fcbad321f',
    messagingSenderId: '699975908686',
    projectId: 'quick-notes-firebase-f66e7',
    authDomain: 'quick-notes-firebase-f66e7.firebaseapp.com',
    storageBucket: 'quick-notes-firebase-f66e7.firebasestorage.app',
    measurementId: 'G-X0VW48JX14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoFL-s0w2xyuPHMM_vWj7JD-JdSVTNwhI',
    appId: '1:699975908686:android:cba106c74af69076ad321f',
    messagingSenderId: '699975908686',
    projectId: 'quick-notes-firebase-f66e7',
    storageBucket: 'quick-notes-firebase-f66e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4RPnzw1go_yAiLUmZp9drROCGK5-cdh0',
    appId: '1:699975908686:ios:88175b4ae87b6fb3ad321f',
    messagingSenderId: '699975908686',
    projectId: 'quick-notes-firebase-f66e7',
    storageBucket: 'quick-notes-firebase-f66e7.firebasestorage.app',
    iosBundleId: 'com.example.quickNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4RPnzw1go_yAiLUmZp9drROCGK5-cdh0',
    appId: '1:699975908686:ios:88175b4ae87b6fb3ad321f',
    messagingSenderId: '699975908686',
    projectId: 'quick-notes-firebase-f66e7',
    storageBucket: 'quick-notes-firebase-f66e7.firebasestorage.app',
    iosBundleId: 'com.example.quickNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA30YQU_UAML4nkyhJycTuXtSsvr1-PzJ0',
    appId: '1:699975908686:web:00e356e6449205d3ad321f',
    messagingSenderId: '699975908686',
    projectId: 'quick-notes-firebase-f66e7',
    authDomain: 'quick-notes-firebase-f66e7.firebaseapp.com',
    storageBucket: 'quick-notes-firebase-f66e7.firebasestorage.app',
    measurementId: 'G-VWQZYC4CCT',
  );

}